package Disilon;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedHashMap;

public class ActorStats {
    public String name;
    public int ml;
    public int cl;
    public int tier;
    public double hp_max;
    public double hp;
    public double mp_max;
    public double mp;
    public double atk;
    public double def;
    public double intel;
    public double resist;
    public double hit;
    public double speed;
    public double water;
    public double fire;
    public double wind;
    public double earth;
    public double light;
    public double dark;

    public double base_hp_max;
    public double base_atk;
    public double base_def;
    public double base_int;
    public double base_res;
    public double base_hit;
    public double base_speed;
    public double base_fire;
    public double base_water;
    public double base_wind;
    public double base_earth;
    public double base_light;
    public double base_dark;
    public double base_exp;
    public double base_water_res;
    public double base_fire_res;
    public double base_wind_res;
    public double base_earth_res;
    public double base_light_res;
    public double base_dark_res;
    public double base_phys_res;
    public double base_magic_res;

    public double gear_atk;
    public double gear_def;
    public double gear_int;
    public double gear_res;
    public double gear_hit;
    public double gear_speed;
    public double gear_hp;
    public double gear_water;
    public double gear_fire;
    public double gear_wind;
    public double gear_earth;
    public double gear_light;
    public double gear_dark;
    public double gear_crit;
    public double gear_burn;
    public double gear_stun;
    public double gear_barrier;

    public double set_hit = 1;
    public double set_res = 1;
    public double set_magicdmg = 1;
    public double set_physdmg = 1;
    public double set_mit1 = 0;
    public double set_mit2 = 0;
    public double set_core = 0;
    public double set_exp = 0;
    public double set_training = 0;
    public double set_water = 1;
    public double set_fire = 1;
    public double set_earth = 1;
    public double set_mana = 0;
    public double set_squirrel_drop = 1;
    public double set_squirrel_rate = 100;

    public double hp_mult = 1;
    public double mp_mult = 1;
    public double atk_mult = 1;
    public double int_mult = 1;
    public double def_mult = 1;
    public double res_mult = 1;
    public double hit_mult = 1;
    public double speed_mult = 1;
    public double dodge_mult = 1;

    public double water_res;
    public double fire_res;
    public double wind_res;
    public double earth_res;
    public double light_res;
    public double dark_res;
    public double phys_res;
    public double magic_res;

    public double dmg_mult = 1;
    public double burn_mult = 1;
    public double poison_mult = 1;
    public double ailment_res = 1;
    public ActiveSkill prepare;
    public double prepare_threshold;
    public double exp;
    public double exp_mult = 1;
    public double mp_cost_add;
    public double mp_cost_mult = 1;
    public double cast_speed_mult = 1;
    public double delay_speed_mult = 1;

    public double hide_bonus = 0;
    public boolean smoked = false;
    public double bound = 0;
    public boolean ambushing = false;
    public double charge;
    public boolean remove_charge = false;
    public double def_break = 0;
    public double res_break = 0;
    public double weaken = 0;
    public double slow = 1;
    public double mark = 0;
    public double empower_hp = 0;
    public double hp_regen = 0;
    public double blessed = 0;
    public double elemental_buff = 0;
    public double bless_boost = 1;
    public double bless_duration = 0;
    public double core_mult = 0;
    public double drop_mult = 1;
    public double counter_strike = 0;
    public double multi_arrows = 0;
    public double finke_bonus = 0;
    public double cl_exp;
    public double ml_exp;
    public boolean lvling = false;
    public double old_ml;
    public double old_cl;
    public boolean counter_dodge = false;
    public boolean counter_heal = false;
    public double stun_time = 0;
    public ActiveSkill last_skill;
    public ActiveSkill casting;
    public Zone zone = null;
    public double dot_tracking = 0;
    public double overkill = 0;
    public double damage_taken = 0;
    public boolean holylight_enabled;
    public boolean prayer_enabled;
    public boolean aurablade_enabled;
    public boolean eblast_enabled;
    public double milestone_exp_mult = 1;
    public double r_spd_bonus = 0;
    public double old_milestone_exp_mult = 1;
    public boolean current_skill_hit = false;
    public double ambush_bonus = 0;
    public Actor target;
    public boolean last_crit = false;
    public int max_skill_lvl = 20;
    public double dmg_range = 0;
    public int enemy_min_lvl = 0;
    public boolean enemy_min_lvl_enabled = true;
    public double base_crit_chance = 0;
    public double base_crit_damage = 1.5;
    public double no_overkill_crit = 0;
    public double core_drop_research = 0;
    public double core_quality_research = 0;

    public ActiveSkill skill1;
    public ActiveSkill skill2;
    public ActiveSkill skill3;
    public ActiveSkill skill4;
    public Potion potion1;
    public Potion potion2;
    public Potion potion3;

    public ArrayList<Debuff> debuffs = new ArrayList<Debuff>();
    public ArrayList<Buff> buffs = new ArrayList<Buff>();
    public ArrayList<Debuff> pending_debuffs = new ArrayList<Debuff>();
    public ArrayList<Buff> pending_buffs = new ArrayList<Buff>();
    public LinkedHashMap<String, PassiveSkill> passives = new LinkedHashMap<String, PassiveSkill>();
    public LinkedHashMap<String, ActiveSkill> active_skills = new LinkedHashMap<String, ActiveSkill>();
    public SkillData skills = new SkillData(this, active_skills, passives);
    public LinkedHashMap<String, Equipment> equipment = new LinkedHashMap<String, Equipment>();
    public LinkedHashMap<String, EquipmentSet> sets = new LinkedHashMap<String, EquipmentSet>();
    public HashMap<String, Double> research_lvls;
    public HashMap<String, Double> research_old_lvls;
    public HashMap<String, Double> research_weight;
}
